apiVersion: v1
kind: LimitRange
metadata:
  name: namespace-limitrange
spec:
  limits:
  - type: Container
    default:
      cpu: {{ .Values.namespace.limitRange.default.cpu | quote }}
      memory: {{ .Values.namespace.limitRange.default.memory | quote }}
    defaultRequest:
      cpu: {{ .Values.namespace.limitRange.defaultRequest.cpu | quote }}
      memory: {{ .Values.namespace.limitRange.defaultRequest.memory | quote }}
    max:
      cpu: {{ .Values.namespace.limitRange.max.cpu | quote }}
      memory: {{ .Values.namespace.limitRange.max.memory | quote }}
