apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
spec:
  hard:
    pods: {{ .Values.namespace.quota.pods | quote }}
    requests.cpu: {{ .Values.namespace.quota.requestsCpu | quote }}
    requests.memory: {{ .Values.namespace.quota.requestsMemory | quote }}
    limits.cpu: {{ .Values.namespace.quota.limitsCpu | quote }}
    limits.memory: {{ .Values.namespace.quota.limitsMemory | quote }}
